name: eco_sfera
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^9.2.2
  flutter_localizations:
    sdk: flutter
  intl: any
  google_fonts: ^6.2.1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  shared_preferences: ^2.3.2
  connectivity: ^3.0.6
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator:
  build_runner:

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
           style: normal
         - asset: assets/fonts/Montserrat/static/Montserrat-Italic.ttf
           style: italic

flutter_intl:
  enabled: true
  class_name: AppLocalization
  arb-dir: lib/l10n
  preferred-supported-locales:
    - en
    - es
  use-deferred-loading: true