name: eco_sfera
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  alice:
    path: domain/alice
  app_bloc:
    path: app/app_bloc
  core:
    path: domain/core
  cupertino_icons: ^1.0.8
  database:
    path: data/database
  design_system:
    path: app/design_system
  flutter:
    sdk: flutter
  flutter_native_splash: 2.4.1
  map_service:
    path: data/map_service
  navigation:
    path: app/navigation
  network:
    path: data/network
  firebase_eco:
    path: data/firebase_eco
  repository:
    path: domain/repository
  use_case:
    path: domain/use_case

dev_dependencies:
  build_runner: 2.4.10
  change_app_package_name: 1.3.0

  flutter_launcher_icons: 0.13.1
  flutter_test:
    sdk: flutter
  injectable_generator: 2.6.1
  melos: ^6.1.0
  very_good_analysis: ^7.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/audio/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app.png"
  remove_alpha_ios: true
