name: core
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  auto_route: 8.3.0
  connectivity_plus: 6.0.4
  easy_localization: 3.0.7
  easy_localization_loader: 2.0.2
  envied: 0.5.4+1
  equatable: 2.0.5
  alice:
    path: ../alice
  flutter:
    sdk: flutter
  flutter_local_notifications: 17.2.1+2
  flutter_multi_formatter: 2.13.0
  freezed_annotation: 2.4.4
  geocoding: 3.0.0
  get_it: 7.7.0
  google_maps_flutter: 2.9.0
  injectable: 2.4.4
  internet_connection_checker: 1.0.0+1
  intl: 0.19.0
  json_annotation: 4.9.0
  map_launcher: 3.3.1
  mask_text_input_formatter: 2.9.0
  package_info_plus: 8.0.1
  permission_handler: 11.3.1
  rxdart: 0.28.0
  synchronized: 3.1.0+1
  share_plus: 10.0.0
  url_launcher: 6.3.0
  yandex_geocoder: 2.3.1
#  google_fonts: ^6.2.1

dev_dependencies:
  auto_route_generator: 8.0.0
  build_runner: 2.4.10
  envied_generator: 0.5.4+1

  flutter_test:
    sdk: flutter

  injectable_generator: 2.6.2
  json_serializable: 6.8.0
  very_good_analysis: 5.1.0

flutter:
  assets:
    - assets/translations/